
package restog6.Vistas;

import data.Conexion;
import data.MesaData;

/**
 * @author Grupo 6
 * Fernandez Valentina
 * Romero Jorge
 * Manuel Gutierrez
 */
public class MesaView extends javax.swing.JInternalFrame {
    private MesaData mesaData;
    /**
     * Creates new form MesaView
     */
    public MesaView(Conexion conexion) {
        initComponents();
        this.setTitle("Registro de Mesas");
        mesaData = new MesaData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jbAgregarMesa = new javax.swing.JButton();
        jbModificarMesa = new javax.swing.JButton();
        jbHabilitarDeshabilitarMesa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jlTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlTitulo.setText("Registro de Mesas");
        jlTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbAgregarMesa.setText("Agregar Mesa");
        jbAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarMesaActionPerformed(evt);
            }
        });

        jbModificarMesa.setText("Modificar Mesa");
        jbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMesaActionPerformed(evt);
            }
        });

        jbHabilitarDeshabilitarMesa.setText("Habilitar/Deshabilitar Mesa");
        jbHabilitarDeshabilitarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHabilitarDeshabilitarMesaActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbHabilitarDeshabilitarMesa)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jlTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(173, 173, 173)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbAgregarMesa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbModificarMesa, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(51, 51, 51)
                .addComponent(jbAgregarMesa)
                .addGap(42, 42, 42)
                .addComponent(jbModificarMesa)
                .addGap(46, 46, 46)
                .addComponent(jbHabilitarDeshabilitarMesa)
                .addGap(34, 34, 34)
                .addComponent(jButton4)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarMesaActionPerformed
        MesaView_Agregar ventanaAgregar = new MesaView_Agregar(mesaData);
        
        Menu.jDesktopPane1.add(ventanaAgregar);
        ventanaAgregar.toFront();
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_jbAgregarMesaActionPerformed

    private void jbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMesaActionPerformed
        MesaView_Modificar ventanaModificar = new MesaView_Modificar(mesaData);
        
        Menu.jDesktopPane1.add(ventanaModificar);
        ventanaModificar.toFront();
        ventanaModificar.setVisible(true);
    }//GEN-LAST:event_jbModificarMesaActionPerformed

    private void jbHabilitarDeshabilitarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHabilitarDeshabilitarMesaActionPerformed
        MesaView_HabilitacionesMesa ventanaHabilitaciones = new MesaView_HabilitacionesMesa(mesaData);
        
        Menu.jDesktopPane1.add(ventanaHabilitaciones);
        ventanaHabilitaciones.toFront();
        ventanaHabilitaciones.setVisible(true);
    }//GEN-LAST:event_jbHabilitarDeshabilitarMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jbAgregarMesa;
    private javax.swing.JButton jbHabilitarDeshabilitarMesa;
    private javax.swing.JButton jbModificarMesa;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
