
package restog6.Vistas;

import data.MesaData;
import javax.swing.JOptionPane;
import modelos.Mesa;

/**
 * @author Grupo 6
 * Fernandez Valentina
 * Romero Jorge
 * Manuel Gutierrez
 */
public class MesaView_Agregar extends javax.swing.JInternalFrame {
    private MesaData mesaData;
    
    /**
     * Creates new form MesaView_Agregar
     */
    public MesaView_Agregar(MesaData mesaData) {
        initComponents();
        this.mesaData = mesaData;
        this.setTitle("Agregar Mesa");
        llenarComboBoxCapacidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTituloAgregar = new javax.swing.JLabel();
        jlCapacidad = new javax.swing.JLabel();
        jcbCapacidad = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();
        jlMensaje = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);

        jlTituloAgregar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlTituloAgregar.setText("Agregar una Mesa");

        jlCapacidad.setText("Capacidad");

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jlMensaje.setText("Las Mesas Nuevas Están Libres y Activas");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTituloAgregar)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlCapacidad)
                        .addGap(18, 18, 18)
                        .addComponent(jcbCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jlMensaje)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTituloAgregar)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCapacidad)
                    .addComponent(jcbCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregar)
                    .addComponent(jbCancelar))
                .addGap(18, 18, 18)
                .addComponent(jlMensaje)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        Mesa mesaNueva = new Mesa((Integer)jcbCapacidad.getSelectedItem(), 'L', true);
        
        if(mesaData.agregarMesa(mesaNueva)){
            JOptionPane.showMessageDialog(this, "Nueva Mesa Agregada!\n\tNro Mesa Generado: " + mesaNueva.getIdMesa());
            this.dispose();
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void llenarComboBoxCapacidad(){
        for(int i = 2; i <= 6; i+=2){
            jcbCapacidad.addItem(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<Integer> jcbCapacidad;
    private javax.swing.JLabel jlCapacidad;
    private javax.swing.JLabel jlMensaje;
    private javax.swing.JLabel jlTituloAgregar;
    // End of variables declaration//GEN-END:variables
}
