
package restog6.Vistas;

import data.MesaData;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import modelos.Mesa;

/**
 * @author Grupo 6
 * Fernandez Valentina
 * Romero Jorge
 * Manuel Gutierrez
 */
public class MesaView_Modificar extends javax.swing.JInternalFrame {
    private MesaData mesaData;
    /**
     * Creates new form MesaView_Modificar
     */
    public MesaView_Modificar(MesaData mesaData) {
        initComponents();
        this.setTitle("Modificar Mesa");
        this.mesaData = mesaData;
        llenarComboBoxMesas();
        llenarComboBoxCapacidadNueva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEstado = new javax.swing.ButtonGroup();
        jlModificarMesa = new javax.swing.JLabel();
        jlElegirMesa = new javax.swing.JLabel();
        jcbMesas = new javax.swing.JComboBox<>();
        jlCapacidadNueva = new javax.swing.JLabel();
        jcbCapacidadNueva = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jrbLibre = new javax.swing.JRadioButton();
        jrbOcupada = new javax.swing.JRadioButton();
        jrbAtendida = new javax.swing.JRadioButton();
        jbGuardarCambios = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setClosable(true);

        jlModificarMesa.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlModificarMesa.setText("Modificar Mesa");

        jlElegirMesa.setText("Elegir Mesa");

        jlCapacidadNueva.setText("Capacidad Nueva");

        jLabel1.setText("Estado");

        grupoEstado.add(jrbLibre);
        jrbLibre.setText("Libre");

        grupoEstado.add(jrbOcupada);
        jrbOcupada.setText("Ocupada");

        grupoEstado.add(jrbAtendida);
        jrbAtendida.setText("Atendida");

        jbGuardarCambios.setText("Guardar Cambios");
        jbGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarCambiosActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jlModificarMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCapacidadNueva)
                                .addGap(18, 18, 18)
                                .addComponent(jcbCapacidadNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbLibre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrbOcupada))
                                    .addComponent(jbGuardarCambios))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbAtendida)
                                    .addComponent(jbCancelar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jlElegirMesa)
                        .addGap(18, 18, 18)
                        .addComponent(jcbMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlModificarMesa)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlElegirMesa)
                    .addComponent(jcbMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCapacidadNueva)
                    .addComponent(jcbCapacidadNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrbLibre)
                    .addComponent(jrbOcupada)
                    .addComponent(jrbAtendida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarCambios)
                    .addComponent(jbCancelar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarCambiosActionPerformed
        if(jrbAtendida.isSelected() || jrbLibre.isSelected() || jrbOcupada.isSelected()){
            Mesa cambiosMesa = (Mesa)jcbMesas.getSelectedItem();
        
            cambiosMesa.setCapacidad((Integer)jcbCapacidadNueva.getSelectedItem());
            if(jrbLibre.isSelected()){
                cambiosMesa.setEstado('L');
            }else{
                if(jrbOcupada.isSelected()){
                    cambiosMesa.setEstado('O');
                }else{
                    cambiosMesa.setEstado('A');
                }
            }

            if(mesaData.modificarMesa(cambiosMesa)){
                JOptionPane.showMessageDialog(this, "Mesa Modificada!");
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un Estado Por Favor!");
        }
    }//GEN-LAST:event_jbGuardarCambiosActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void llenarComboBoxMesas(){
        ArrayList<Mesa> mesas = mesaData.getMesasActivas();
        
        Collections.sort(mesas, new Comparator<Mesa>(){
            @Override
            public int compare(Mesa t, Mesa t1) {
                if(t.getIdMesa() > t1.getIdMesa()){
                    return 1;
                }else{
                    if(t.getIdMesa() < t1.getIdMesa()){
                        return -1;
                    }else{
                        return 0;
                    }
                }
            }
        });
        
        for(Mesa m : mesas){
            jcbMesas.addItem(m);
        }
    }
    
    private void llenarComboBoxCapacidadNueva(){
        for(int i = 2; i <= 6; i+=2){
            jcbCapacidadNueva.addItem(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardarCambios;
    private javax.swing.JComboBox<Integer> jcbCapacidadNueva;
    private javax.swing.JComboBox<Mesa> jcbMesas;
    private javax.swing.JLabel jlCapacidadNueva;
    private javax.swing.JLabel jlElegirMesa;
    private javax.swing.JLabel jlModificarMesa;
    private javax.swing.JRadioButton jrbAtendida;
    private javax.swing.JRadioButton jrbLibre;
    private javax.swing.JRadioButton jrbOcupada;
    // End of variables declaration//GEN-END:variables
}
