
package restog6.Vistas;

import data.Conexion;
import data.MesaData;

/**
 * @author Grupo 6
 * Fernandez Valentina
 * Romero Jorge
 * Manuel Gutierrez
 */
public class MesaView extends javax.swing.JInternalFrame {
    private MesaData mesaData;
    
    private MesaView_Agregar ventanaAgregar = null;
    private MesaView_Modificar ventanaModificar = null;
    private MesaView_HabilitacionesMesa ventanaHabilitaciones = null;
    
    /**
     * Creates new form MesaView
     */
    public MesaView(Conexion conexion) {
        initComponents();
        this.setTitle("Registro de Mesas");
        mesaData = new MesaData(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jbAgregarMesa = new javax.swing.JButton();
        jbModificarMesa = new javax.swing.JButton();
        jbHabilitarDeshabilitarMesa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jlAgregarMesaNueva = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jlTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlTitulo.setText("Registro de Mesas");
        jlTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbAgregarMesa.setText("Agregar Mesa");
        jbAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarMesaActionPerformed(evt);
            }
        });

        jbModificarMesa.setText("Modificar Mesa");
        jbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMesaActionPerformed(evt);
            }
        });

        jbHabilitarDeshabilitarMesa.setText("Habilitar/Deshabilitar Mesa");
        jbHabilitarDeshabilitarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHabilitarDeshabilitarMesaActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jlAgregarMesaNueva.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jlAgregarMesaNueva.setText("Agregar una Mesa Nueva");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Modificar una Mesa");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Habilitar o Deshabilitar una Mesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbModificarMesa)
                            .addComponent(jbAgregarMesa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jlAgregarMesaNueva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jbHabilitarDeshabilitarMesa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addGap(26, 26, 26)
                .addComponent(jlAgregarMesaNueva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAgregarMesa)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbModificarMesa)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbHabilitarDeshabilitarMesa)
                .addGap(24, 24, 24)
                .addComponent(jButton4)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarMesaActionPerformed
        if(ventanaAgregar == null){
            ventanaAgregar = new MesaView_Agregar(mesaData);
            
            if(ventanaModificar != null){
                ventanaModificar.dispose();
                ventanaModificar = null;
            }
            
            if(ventanaHabilitaciones != null){
                ventanaHabilitaciones.dispose();
                ventanaHabilitaciones = null;
            }
        
            Menu.jDesktopPane1.add(ventanaAgregar);
            ventanaAgregar.toFront();
            ventanaAgregar.setVisible(true);
        }else{
            ventanaAgregar.dispose();
            
            if(ventanaModificar != null){
                ventanaModificar.dispose();
                ventanaModificar = null;
            }
            
            if(ventanaHabilitaciones != null){
                ventanaHabilitaciones.dispose();
                ventanaHabilitaciones = null;
            }
            
            ventanaAgregar = new MesaView_Agregar(mesaData);
            
            Menu.jDesktopPane1.add(ventanaAgregar);
            ventanaAgregar.toFront();
            ventanaAgregar.setVisible(true);
        }
    }//GEN-LAST:event_jbAgregarMesaActionPerformed

    private void jbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMesaActionPerformed
        if(ventanaModificar == null){
            ventanaModificar = new MesaView_Modificar(mesaData);
            
            if(ventanaAgregar != null){
                ventanaAgregar.dispose();
                ventanaAgregar = null;
            }
            if(ventanaHabilitaciones != null){
                ventanaHabilitaciones.dispose();
                ventanaHabilitaciones = null;
            }
        
            Menu.jDesktopPane1.add(ventanaModificar);
            ventanaModificar.toFront();
            ventanaModificar.setVisible(true);
        }else{
            ventanaModificar.dispose();
            
            if(ventanaAgregar != null){
                ventanaAgregar.dispose();
                ventanaAgregar = null;
            }
            if(ventanaHabilitaciones != null){
                ventanaHabilitaciones.dispose();
                ventanaHabilitaciones = null;
            }
            
            ventanaModificar = new MesaView_Modificar(mesaData);
        
            Menu.jDesktopPane1.add(ventanaModificar);
            ventanaModificar.toFront();
            ventanaModificar.setVisible(true);
        }
    }//GEN-LAST:event_jbModificarMesaActionPerformed

    private void jbHabilitarDeshabilitarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHabilitarDeshabilitarMesaActionPerformed
        if(ventanaHabilitaciones == null){
            ventanaHabilitaciones = new MesaView_HabilitacionesMesa(mesaData);
            
            if(ventanaAgregar != null){
                ventanaAgregar.dispose();
                ventanaAgregar = null;
            }
            if(ventanaModificar != null){
                ventanaModificar.dispose();
                ventanaModificar = null;
            }
        
            Menu.jDesktopPane1.add(ventanaHabilitaciones);
            ventanaHabilitaciones.toFront();
            ventanaHabilitaciones.setVisible(true);
        }else{
            ventanaHabilitaciones.dispose();
            
            if(ventanaAgregar != null){
                ventanaAgregar.dispose();
                ventanaAgregar = null;
            }
            if(ventanaModificar != null){
                ventanaModificar.dispose();
                ventanaModificar = null;
            }
            
            ventanaHabilitaciones = new MesaView_HabilitacionesMesa(mesaData);
        
            Menu.jDesktopPane1.add(ventanaHabilitaciones);
            ventanaHabilitaciones.toFront();
            ventanaHabilitaciones.setVisible(true);
        }
    }//GEN-LAST:event_jbHabilitarDeshabilitarMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbAgregarMesa;
    private javax.swing.JButton jbHabilitarDeshabilitarMesa;
    private javax.swing.JButton jbModificarMesa;
    private javax.swing.JLabel jlAgregarMesaNueva;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
