

package restog6.Vistas;

import data.Conexion;
import data.MesaData;
import data.ReservaData;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Reserva;

/**
 * @author Grupo 6
 * Fernandez Valentina
 * Romero Jorge
 * Manuel Gutierrez
 */
public class ReservaView extends javax.swing.JInternalFrame {
    private MesaData mesaData;
    private ReservaData reservaData;
    private ArrayList<Reserva> listaReservas;
    private DefaultTableModel modeloTabla;
    
    private Comparator<Reserva> compaID;
    
    /** Creates new form ReservaView */
    public ReservaView(Conexion conexion) {
        initComponents();
        
        this.setTitle("Reserva de Mesas");
        
        this.mesaData = new MesaData(conexion);
        this.reservaData = new ReservaData(conexion);
        this.modeloTabla = new DefaultTableModel();
        
        armarTabla();
        
        compaID = new Comparator<Reserva>(){
            @Override
            public int compare(Reserva r, Reserva r1){
                if(r.getIdReserva() < r1.getIdReserva()){
                    return -1;
                }else{
                    if(r.getIdReserva() > r1.getIdReserva()){
                        return 1;
                    }else{
                        return 0;
                    }
                }
            }
        };
        
        cargarReservasEnTabla(compaID);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlReservaMesas = new javax.swing.JLabel();
        jbNuevaReserva = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReservasActivas = new javax.swing.JTable();
        jlReservasActivas = new javax.swing.JLabel();
        jbCancelarReserva = new javax.swing.JButton();
        jbRefrescarTabla = new javax.swing.JButton();
        jbModificarReserva = new javax.swing.JButton();
        jbNombreCliente = new javax.swing.JButton();
        jbFechaReserva = new javax.swing.JButton();
        jlOrdenarPor = new javax.swing.JLabel();

        setResizable(true);

        jlReservaMesas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlReservaMesas.setText("Reserva de Mesas");

        jbNuevaReserva.setText("Nueva Reserva");
        jbNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaReservaActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtReservasActivas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtReservasActivas);

        jlReservasActivas.setText("Reservas Activas");

        jbCancelarReserva.setText("Cancelar Reserva");
        jbCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarReservaActionPerformed(evt);
            }
        });

        jbRefrescarTabla.setText("Refrescar Tabla");
        jbRefrescarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarTabla(evt);
            }
        });

        jbModificarReserva.setText("Modificar Reserva");
        jbModificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarReservaActionPerformed(evt);
            }
        });

        jbNombreCliente.setText("Nombre Cliente");
        jbNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNombreClienteActionPerformed(evt);
            }
        });

        jbFechaReserva.setText("Fecha Reserva");
        jbFechaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechaReservaActionPerformed(evt);
            }
        });

        jlOrdenarPor.setText("Ordenar Por");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlReservasActivas)
                        .addGap(69, 69, 69)
                        .addComponent(jbRefrescarTabla)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jlOrdenarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbNombreCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbFechaReserva))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbNuevaReserva)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbCancelarReserva)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbModificarReserva)
                                    .addGap(27, 27, 27)
                                    .addComponent(jbCancelar))))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlReservaMesas)
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlReservaMesas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRefrescarTabla)
                    .addComponent(jlReservasActivas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFechaReserva)
                    .addComponent(jbNombreCliente)
                    .addComponent(jlOrdenarPor))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbModificarReserva)
                    .addComponent(jbCancelarReserva)
                    .addComponent(jbNuevaReserva))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaReservaActionPerformed
        ReservaView_Reservar ventanaReservar = new ReservaView_Reservar(mesaData, reservaData);
        
        Menu.jDesktopPane1.add(ventanaReservar);
        ventanaReservar.toFront();
        ventanaReservar.setVisible(true);

    }//GEN-LAST:event_jbNuevaReservaActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarReservaActionPerformed
        Reserva reservaSeleccionada;
        if(jtReservasActivas.getSelectedRow() != -1){
            int filaSelect = jtReservasActivas.getSelectedRow();
            
            int idReserva = (Integer)modeloTabla.getValueAt(filaSelect, 0);
            String nombre = (String)modeloTabla.getValueAt(filaSelect, 1);
            
            if(JOptionPane.showConfirmDialog(this, "Confirmar Cancelación de la Reserva " + idReserva + "\nDel Cliente " + nombre) == 0){
                if(reservaData.borrarReserva(idReserva)){
                    JOptionPane.showMessageDialog(this, "Reserva Cancelada!");
                    borrarFilasTabla();
                    cargarReservasEnTabla(compaID);
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una Reserva para Cancelarla!");
        }
        
    }//GEN-LAST:event_jbCancelarReservaActionPerformed

    private void refrescarTabla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarTabla
        borrarFilasTabla();
        cargarReservasEnTabla(compaID);
    }//GEN-LAST:event_refrescarTabla

    /**
     * Solo se puede modificar la mesa, la hora y el día
     * @param evt click
     */
    private void jbModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarReservaActionPerformed
        if(jtReservasActivas.getSelectedRow() != -1){
            int filaSelect = jtReservasActivas.getSelectedRow();
            
            int idReservaSeleccionada = (Integer)modeloTabla.getValueAt(filaSelect, 0);
            
            Reserva reservaSeleccionada = reservaData.getReservaPorId(idReservaSeleccionada);
            
            ReservaView_Modificar ventanaModificar = new ReservaView_Modificar(reservaData, mesaData, reservaSeleccionada);
            
            Menu.jDesktopPane1.add(ventanaModificar);
            ventanaModificar.toFront();
            ventanaModificar.setVisible(true);
        }
        
    }//GEN-LAST:event_jbModificarReservaActionPerformed

    private void jbNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNombreClienteActionPerformed
        borrarFilasTabla();
        
        cargarReservasEnTabla(new Comparator<Reserva>(){
            @Override
            public int compare(Reserva r, Reserva r1){
                return r.getNombreCliente().compareTo(r1.getNombreCliente());
            }
        });
    }//GEN-LAST:event_jbNombreClienteActionPerformed

    private void jbFechaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechaReservaActionPerformed
        borrarFilasTabla();
        
        cargarReservasEnTabla(new Comparator<Reserva>(){
            @Override
            public int compare(Reserva r, Reserva r1){
                if(r.getFechaReserva().isBefore(r1.getFechaReserva())){
                    return -1;
                }else{
                    if(r.getFechaReserva().isAfter(r1.getFechaReserva())){
                        return 1;
                    }else{
                        return 0;
                    }
                }
            }
        });
    }//GEN-LAST:event_jbFechaReservaActionPerformed

    /**
     * Arma el Modelo de la Tabla
     */
    private void armarTabla(){
        ArrayList<Object> columnas = new ArrayList<>();
        
        columnas.add("ID");
        columnas.add("Cliente");
        columnas.add("DNI");
        columnas.add("Fecha y Hora");
        columnas.add("Mesa");
        
        for(Object col : columnas){
            modeloTabla.addColumn(col);
        }
        
        jtReservasActivas.setModel(modeloTabla);
    }
    
    /**
     * Llena la Tabla con las Reservas Activas
     */
    private void cargarReservasEnTabla(Comparator compa){
        listaReservas = reservaData.getReservasActivas();
        
        Collections.sort(listaReservas, compa);
        
        for(Reserva r : listaReservas){
            String horaYFecha = r.getFechaReserva().toString();
            horaYFecha = horaYFecha.replace("T", " ");
            modeloTabla.addRow(new Object[]{
                r.getIdReserva(), r.getNombreCliente(), r.getDniCliente(), horaYFecha, r.getMesa().getIdMesa()
            });
        }
    }
    
    /**
     * Limpia la Tabla
     */
    private void borrarFilasTabla() {
        int a = modeloTabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelarReserva;
    private javax.swing.JButton jbFechaReserva;
    private javax.swing.JButton jbModificarReserva;
    private javax.swing.JButton jbNombreCliente;
    private javax.swing.JButton jbNuevaReserva;
    private javax.swing.JButton jbRefrescarTabla;
    private javax.swing.JLabel jlOrdenarPor;
    private javax.swing.JLabel jlReservaMesas;
    private javax.swing.JLabel jlReservasActivas;
    private javax.swing.JTable jtReservasActivas;
    // End of variables declaration//GEN-END:variables

}
